apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: scada-system
spec:
  replicas: 2

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-sa
      
      containers:
        - name: backend
          image: elashrypublic/scada-backend:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: backend-config

          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: APP_KEY

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /api/scada-data
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/scada-data
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"