apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: scada-system
type: Opaque
stringData:
  APP_KEY: "base64:VYkot/f8qaPncPVEFu4n/RQMloQNxLn1E7ofeO1Ca/s="
  DB_PASSWORD: "StrongPass123!"