apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scada-ingress
  namespace: scada-system
spec:
  ingressClassName: nginx

  rules:
    - host: scada.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80