apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: scada-system
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Root@123
  MYSQL_DATABASE: scada_db
  MYSQL_USER: scada_user
  MYSQL_PASSWORD: StrongPass123!