apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-sql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /home/u1/Desktop/final-project/docker/mysql/init