apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: {{ .Values.backend.strategy.maxSurge }}
      maxUnavailable: {{ .Values.backend.strategy.maxUnavailable }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: backend-config

          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: APP_KEY

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /api/scada-data
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/scada-data
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5

          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}

            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}